moved store into app.js
jefflueck/Training-App pull request #1
Opened 2018-03-20 17:18 UTC by jefflueck

moved store code into app.js file

2018-04-04 01:53 UTC, timgremore requested changes
👍 this looks great! Nice work!

2018-04-04 01:53 UTC, timgremore commented on webpack.config.js
> +	entry: './src/app.js',
@jefflueck this is nitpicking but feedback you will get from most PR reviews - `entry` should be aligned vertically with `output`

2018-04-07 12:21 UTC, jefflueck commented on webpack.config.js
> +	entry: './src/app.js',
Ok not sure what you mean by that. Are you saying the code order should be realigned, or that the output needs to change?

2018-04-09 12:38 UTC, timgremore commented on webpack.config.js
> +	entry: './src/app.js',
yep - `entry` should be aligned with `output` (and `module`, `devtool`, `devServer`)

2018-04-09 14:14 UTC, timgremore commented
Looks great @jefflueck - would you please squash these 2 commits into 1? After that we can merge. Here is one article explaining rebasing: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2018-04-17 16:41 UTC, closed without merging